
import java.awt.Color;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.awt.*;
import java.awt.geom.*;
import javax.swing.JPanel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author davidetumminello
 */
public class AnthiteticVariatesDialog extends javax.swing.JFrame {

    //private UI ui;
    private float[][] risultati = new float[18][2];
    DecimalFormat df;
    int index;
    //FrameGraphHitOrMiss HOMGraph;
    
    public AnthiteticVariatesDialog(){
        //ui = new UI();
        initComponents();
        index = 0;
        df = new DecimalFormat("##.##");
        
    }
    
    public void setRisultati(float risultati[][]){
        //stampaRisultati();
        this.risultati = risultati;
    }
    
    public void stampaRisultati(){
        for(int i=0;i<5;i++)
            System.out.println("DIALOG : "+risultati[i][0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        theta_result = new javax.swing.JLabel();
        dev_standard_result = new javax.swing.JLabel();
        confidence_result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(650, 650));

        jLabel1.setText("Risultati Algoritmo Variabile Antitetica");

        jLabel2.setText("N");

        jLabel3.setText("Theta");

        jLabel4.setText("Dev. Standard");

        jLabel5.setText("Inter. di confidenza");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "10", "100", "1000", "10000", "100000", "1000000" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(confidence_result, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dev_standard_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(theta_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, 0))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(theta_result, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(dev_standard_result, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(confidence_result, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {                                    
        df.setRoundingMode(RoundingMode.UP);
        theta_result.setText(df.format(risultati[jList1.getSelectedIndex()][0])+"");
        theta_result.setForeground(Color.red);
        dev_standard_result.setText(df.format(risultati[jList1.getSelectedIndex()+6][0])+"");
        dev_standard_result.setForeground(Color.red);
        confidence_result.setText("[ "+df.format(risultati[jList1.getSelectedIndex()+11][0])+" ; "+df.format(risultati[jList1.getSelectedIndex()+11][1])+" ]");
        confidence_result.setForeground(Color.red);
        index = jList1.getSelectedIndex();
    }                                   

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {                                  
        //System.out.println(evt.getKeyCode());
        //int index = jList1.getSelectedIndex();
        if(evt.getKeyCode() == 40 && index < 5){
            //stampaRisultati();
            df.setRoundingMode(RoundingMode.UP);
            theta_result.setText(df.format(risultati[index+1][0])+"");
            theta_result.setForeground(Color.red);
            dev_standard_result.setText(df.format(risultati[index+1+6][0])+"");
            dev_standard_result.setForeground(Color.red);
            confidence_result.setText("[ "+df.format(risultati[index+1+11][0])+" ; "+df.format(risultati[index+1+11][1])+" ]");
            confidence_result.setForeground(Color.red);
            index++;
        }
        if(evt.getKeyCode() == 38 && index >0){
            df.setRoundingMode(RoundingMode.UP);
            theta_result.setText(df.format(risultati[index-1][0])+"");
            theta_result.setForeground(Color.red);
            dev_standard_result.setText(df.format(risultati[index-1+6][0])+"");
            dev_standard_result.setForeground(Color.red);
            confidence_result.setText("[ "+df.format(risultati[index-1+11][0])+" ; "+df.format(risultati[index-1+11][1])+" ]");
            confidence_result.setForeground(Color.red);
            index--;
        }
    }                                 
    
    /*public void showFrameChart(){
        DefaultCategoryDataset data = new DefaultCategoryDataset();
        data.addValue(risultati[0][0], ""+risultati[0][0] , "10");
        data.addValue(risultati[1][0], ""+risultati[1][0] , "100");
        data.addValue(risultati[2][0], ""+risultati[2][0] , "1000");
        data.addValue(risultati[3][0], ""+risultati[3][0] , "10000");
        data.addValue(risultati[4][0], ""+risultati[4][0] , "100000");
        
                
        JFreeChart graph = ChartFactory.createLineChart (
        "Grafico Theta Hit or Miss",
        "Iterazioni",
        "Theta",
        data,
        PlotOrientation.VERTICAL,
        false,
        false,
        true);
        
        //XYPlot plot = (XYPlot) graph.getPlot ();
        
        //BarRenderer renderer = null;
        CategoryPlot plot = graph.getCategoryPlot();
        //renderer = new BarRenderer();
        ChartFrame frame = new ChartFrame("Frame", graph);
        frame.setVisible(true);
        frame.setSize(400, 400);
        frame.setLocation(300, 10);
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HitOrMissDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HitOrMissDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HitOrMissDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HitOrMissDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HitOrMissDialog().setVisible(true);
            }
        });
    }
    
    /*public void showChart(){
        HOMGraph = new FrameGraphHitOrMiss();
    }*/

    // Variables declaration - do not modify                     
    private javax.swing.JLabel confidence_result;
    private javax.swing.JLabel dev_standard_result;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel theta_result;
    // End of variables declaration                   
}
