import java.awt.*;
import java.awt.geom.*;
import javax.swing.JPanel;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.*;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;

public class FrameGraphHitOrMiss extends javax.swing.JFrame {

    float risultati[][] = new float[18][2];
    int iteration[] = new int [6];
    
    public FrameGraphHitOrMiss() {
        JPanel p = new JPanel();
        p.setSize(480, 500);
        p.add(this.drawGraph());
        this.add(p);
        initComponents();
        
        iteration[0] = 10;
        iteration[1] = 100;
        iteration[2] = 1000;
        iteration[3] = 10000;
        iteration[4] = 100000;
        iteration[5] = 1000000;
        
    }
    
    public void setRisultati(float risultati[][]){
        this.risultati = risultati;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(260, 0));
        setSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public ChartPanel drawGraph (){
        ChartPanel cp;
        XYSeries series = new XYSeries("Serie");
        
        for(int i=0;i<iteration.length;i++)
            series.add (risultati[i][0], iteration[i]);
        
        XYSeriesCollection dataset = new XYSeriesCollection ();
        dataset.addSeries(series);
        
        JFreeChart graph = ChartFactory.createScatterPlot (
        "Grafico Theta Hit or Miss",
        "Iterazioni",
        "Theta",
        dataset,
        PlotOrientation.VERTICAL,
        true,
        true,
        false);
        
        XYPlot plot = (XYPlot) graph.getPlot ();

        XYLineAndShapeRenderer renderer = new XYLineAndShapeRenderer(false, true);
        renderer.setDrawOutlines (false);
        renderer.setUseFillPaint (true);
        renderer.setFillPaint (Color.blue);
        renderer.setShape (new Ellipse2D.Double (-5, -5, 10, 10));
        plot.setRenderer (renderer);
        cp = new ChartPanel(graph);
        return cp;
   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGraphHitOrMiss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGraphHitOrMiss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGraphHitOrMiss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGraphHitOrMiss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGraphHitOrMiss().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

